name: Link Guncelleyici
on:
  schedule:
    - cron: '*/20 * * * *' #
  workflow_dispatch: # Manuel ba≈ülatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: res4kpro

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlink
      
      - name: Execute Script
        run: python main.py config.json
      
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "UPDATE 4KPRO: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin res4kpro
